<a href="https://colab.research.google.com/github/MariyaJosep/Data-Science--Web-Scraping/blob/main/Data_Science_Web_scraping_Flipkart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import requests as req
from bs4 import BeautifulSoup

In [ ]:
page_url = 'https://www.flipkart.com/search?q=mobiles&as=on&as-show=on&otracker=AS_Query_HistoryAutoSuggest_1_2_na_na_na&otracker1=AS_Query_HistoryAutoSuggest_1_2_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=mobiles&requestId=d5cc3575-88f3-43c0-a455-3bceb1644301&as-searchtext=mo&page=1'
page_data = req.get(page_url)

In [ ]:
page_data.content

b'<!doctype html><html lang="en"><head><link href="https://rukminim1.flixcart.com" rel="preconnect"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.905c37.css"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.c46047.css"/><meta http-equiv="Content-type" content="text/html; charset=utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=Edge"/><meta property="fb:page_id" content="102988293558"/><meta property="fb:admins" content="658873552,624500995,100000233612389"/><meta name="robots" content="noodp"/><link rel="shortcut icon" href="https:///www/promos/new/20150528-140547-favicon-retina.ico"/><link type="application/opensearchdescription+xml" rel="search" href="/osdd.xml?v=2"/><meta property="og:type" content="website"/><meta name="og_site_name" property="og:site_name" content="Flipkart.com"/><link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.

In [ ]:
soup = BeautifulSoup(page_data.content, 'html.parser')

In [ ]:
mobile_info = soup.find_all('div', class_='_2kHMtA')

In [ ]:
len(mobile_info)

24

In [ ]:
for mobile in mobile_info:
    pass
#     print(mobile.find('div', class_='_4rR01T'))
#     print(mobile.find('div', class_='_4rR01T').text)
#     print(mobile.find('div', class_='_30jeq3 _1_WHN1').text)

In [ ]:
#creating dataframe from extracting name and price

mobiles = []

for mobile in mobile_info:
    name = mobile.find('div', class_='_4rR01T').text
    price = mobile.find('div', class_='_30jeq3 _1_WHN1').text
    
    mobiles.append({'name':name, 'price':price})
    
    
mobile_ds = pd.DataFrame(mobiles)

In [ ]:
mobile_ds

name    price
0              MOTOROLA e40 (Carbon Gray, 64 GB)   ₹7,999
1                 APPLE iPhone 14 (Blue, 128 GB)  ₹66,999
2   SAMSUNG Galaxy F23 5G (Copper Blush, 128 GB)  ₹16,999
3                  POCO C31 (Shadow Gray, 32 GB)   ₹6,499
4                  POCO C31 (Shadow Gray, 64 GB)   ₹7,749
5        MOTOROLA G62 5G (Midnight Gray, 128 GB)  ₹14,999
6    Infinix HOT 20 Play (Fantasy Purple, 64 GB)   ₹8,199
7   SAMSUNG Galaxy F23 5G (Forest Green, 128 GB)  ₹16,999
8         MOTOROLA G62 5G (Frosted Blue, 128 GB)  ₹14,999
9         REDMI Note 11 SE (Cosmic White, 64 GB)  ₹11,999
10  SAMSUNG Galaxy F23 5G (Copper Blush, 128 GB)  ₹16,999
11     Infinix HOT 20 Play (Aurora Green, 64 GB)   ₹8,199
12     Infinix HOT 20 Play (Racing Black, 64 GB)   ₹8,199
13               POCO M4 Pro (Cool Blue, 128 GB)  ₹12,999
14                  POCO C31 (Royal Blue, 32 GB)   ₹6,499
15         REDMI 9i Sport (Metallic Blue, 64 GB)   ₹7,499
16             REDMI 10 (Caribbean Green, 64 GB)   ₹9,999
17          MOTOROLA g52 (Charcoal Grey, 128 GB)  ₹12,999
18        Infinix HOT 20 Play (Luna Blue, 64 GB)   ₹8,199
19           REDMI 9i Sport (Coral Green, 64 GB)   ₹7,499
20         MOTOROLA g52 (Metallic White, 128 GB)  ₹12,999
21            MOTOROLA G32 (Mineral Gray, 64 GB)  ₹10,499
22              OPPO K10 5G (Ocean Blue, 128 GB)  ₹16,999
23          OPPO K10 5G (Midnight Black, 128 GB)  ₹16,999

In [ ]:
#extracting data from staragile for scrum master

page_url1 = 'https://staragile.com/in/'

page_data1 = req.get(page_url1)

soup1 = BeautifulSoup(page_data1.content, 'html.parser')



In [ ]:
training_info = soup1.find_all('div', class_='row sub-content')

training_info

[<div class="row sub-content"><div class="col-xl-3 col-md-3 col-sm-12 col-12 content-sub1"><span>3,00,000+</span><p>careers advanced</p></div><div class="col-xl-3 col-md-3 col-sm-12 col-12 content-sub"><span>250+</span><p>live classes every month</p></div><div class="col-xl-3 col-md-3 col-sm-12 col-12 content-third"><span>92%</span><p>report career benefits including promotion or a new job</p></div><div class="col-xl-3 col-md-3 col-sm-12 col-12 content-btn page_speed_543201689"><a href="#explore-our-programs"><button class="btn know-btn">EXPLORE COURSES <img class="lazy page_speed_1610150515" data-src="https://staragile.com/public/images/image-webp/arrow.webp" data-srcset="https://staragile.com/public/images/badge-lazy-load.jpg" src="https://staragile.com/public/images/badge-lazy-load.jpg"/></button></a></div></div>]

In [ ]:
for ele in training_info:
    print(ele.find_all('p')[0].text)
    print(ele.find_all('span')[0].text)

careers advanced
3,00,000+


In [ ]:
for p_ele in training_info[0].find_all('p'):
    print(p_ele.text)

careers advanced
live classes every month
report career benefits including promotion or a new job


In [ ]:
for span_ele in training_info[0].find_all('span'):
    print(span_ele.text)

3,00,000+
250+
92%


In [ ]:
courses = soup1.find_all('a')

courses

[<a class="navbar-brand" href="https://staragile.com/in/"><img alt="logo" height="44" src="https://d3w4ndrqcjig4l.cloudfront.net/logo.png" width="160"/></a>,
 <a class="al-crse nav-link">All Courses</a>,
 <a class="nav-link" href="https://staragile.com/blog/">Blog</a>,
 <a class="nav-link" href="https://staragile.com/corporate-training">Corporate</a>,
 <a class="nav-link" href="https://staragile.com/refer-and-earn">Refer &amp; Earn</a>,
 <a class="nav-link" href="https://staragile.com/contact">Contact Us</a>,
 <a class="nav-link" href="http://lms.staragile.com/lms/auth/login" title="Login/Register"><img alt="login" height="16" src="https://d3w4ndrqcjig4l.cloudfront.net/user-login.png" width="16"/></a>,
 <a class="nav-item nav-link active nav-mobile" href="tel:+919513393880">India: +91 95133 93880</a>,
 <a class="nav-item nav-link active nav-mobile" href="tel:+19293562010">USA: +1 929 356 2010</a>,
 <a class="nav-item nav-link active nav-mobile" href="tel:+442039666118">UK: +44 2039 666

In [ ]:
soup1.find_all('div', class_='sub-menu2 page_speed_2099501721')

[]

In [ ]:
ms_url = 'https://powerbi.microsoft.com/en-us/'

ms_page = req.get(ms_url)

ms_soup = BeautifulSoup(ms_page.content, 'html.parser')

In [ ]:
ms_info = ms_soup.find_all('div', class_='column content')

In [ ]:
lists = []
for ele in ms_info:
    head = ele.find('h3').text
    info = ele.find('p').text
    
    lists.append({'head':head, 'info':info})
    
ms_ds = pd.DataFrame(lists)

ms_ds

head  \
0  Get self-service analytics at enterprise scale   
1              Use smart tools for strong results   
2                Help protect your analytics data   

                                                info  
0  Reduce the added cost, complexity, and securit...  
1  Find and share meaningful insights with hundre...  
2  Keep your data secure with industry-leading da...

## Data Preprocessing

In [ ]:
#1. Handling missing values

ds1 = pd.DataFrame({
    'c1':[10, 20, np.nan, 30, np.nan],
    'c2':['apple', 'samsung', 'apple', 'hp', 'hp']
})

ds1

c1       c2
0  10.0    apple
1  20.0  samsung
2   NaN    apple
3  30.0       hp
4   NaN       hp

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
si = SimpleImputer(strategy='mean')

ds1['c1'] = si.fit_transform(ds1[['c1']])

ds1

c1  c2
0  10.0   0
1  20.0   2
2  20.0   0
3  30.0   1
4  20.0   1

In [ ]:
#label encoder
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

columns = ['c2', 'c1']

for col in columns:
    ds1[col] = le.fit_transform(ds1[col])

In [ ]:
ds1

c1  c2
0   0   0
1   1   2
2   1   0
3   2   1
4   1   1

In [ ]:
#one hot encoding

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)

x_ohe = ohe.fit_transform(ds1[['c1']])

In [ ]:
x_ohe

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [ ]:
ds2 = pd.DataFrame({
    'c1':[10,20,30],
    'c2':[10000, 11000, 12000]
})

ds2

c1     c2
0  10  10000
1  20  11000
2  30  12000

In [ ]:
ds12 = ds2
ds13 = ds2

In [ ]:
#normalization and standardization

from sklearn.preprocessing import MinMaxScaler, StandardScaler

ds12 = MinMaxScaler().fit_transform(ds12)
ds13 = StandardScaler().fit_transform(ds13)

In [ ]:
ds12

array([[0. , 0. ],
       [0.5, 0.5],
       [1. , 1. ]])

In [ ]:
ds13

array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

In [ ]:
ds1

c1  c2
0   0   0
1   1   2
2   1   0
3   2   1
4   1   1

In [ ]:
#train test split

from sklearn.model_selection import train_test_split

x = ds1[['c1']] #x always 2D array
y = ds1['c2'] #y always 1D array

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)

#Indepedent Var (x)
#Dependent Var (y)

In [ ]:
x_train.shape

(4, 1)

In [ ]:
x_train

c1
4   1
3   2
0   0
1   1

In [ ]:
x_test

c1
2   1

In [ ]:
emp_ds = pd.read_csv('data/employee.csv')

In [ ]:
emp_ds.shape

(50, 11)

In [ ]:
emp_ds.head(2)

EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          198     Donald  OConnell  DOCONNEL  650.507.9833  21-JUN-07   
1          199    Douglas     Grant    DGRANT  650.507.9844  13-JAN-08   

     JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID  
0  SH_CLERK    2600             -         124             50  
1  SH_CLERK    2600             -         124             50

In [ ]:
x = emp_ds[['PHONE_NUMBER', 'MANAGER_ID', 'EMAIL']]
y = emp_ds['SALARY']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)

In [ ]:
x_train.shape

(40, 3)

In [ ]:
x_test.shape

(10, 3)

In [ ]:
x_train

PHONE_NUMBER MANAGER_ID     EMAIL
5   515.123.7777        101   SMAVRIS
12  590.423.4567        102   AHUNOLD
19  515.124.4269        108     JCHEN
17  515.124.4569        101  NGREENBE
37  650.124.1434        120   SMARKLE
10  515.123.4568        100  NKOCHHAR
38  650.124.5234        121   LBISSOT
25  515.127.4563        114    SBAIDA
34  650.124.1214        120    JNAYER
46  650.121.1234        123   RLADWIG
30  650.123.2234        100    AFRIPP
22  515.124.4567        108     LPOPP
0   650.507.9833        124  DOCONNEL
29  650.123.1234        100    MWEISS
31  650.123.3234        100  PKAUFLIN
2   515.123.4444        101   JWHALEN
4   603.123.6666        201      PFAY
39  650.124.6234        121  MATKINSO
36  650.124.1334        120   JLANDRY
3   515.123.5555        100  MHARTSTE
43  650.127.1834        122   MROGERS
13  590.423.4568        103    BERNST
8   515.123.8181        205    WGIETZ
45  650.127.1634        122  HPHILTAN
33  650.123.5234        100  KMOURGOS
6   515.123.8888        101     HBAER
27  515.127.4565        114   GHIMURO
41  650.124.8234        121   TJOLSON
47  650.121.2034        123   SSTILES
32  650.123.4234        100  SVOLLMAN
42  650.127.1934        122   JMALLIN
40  650.124.7234        121   JAMRLOW
24  515.127.4562        114     AKHOO
35  650.124.1224        120  IMIKKILI
11  515.123.4569        100   LDEHAAN
14  590.423.4569        103   DAUSTIN
21  515.124.4469        108   JMURMAN
26  515.127.4564        114   STOBIAS
20  515.124.4369        108  ISCIARRA
23  515.127.4561        100  DRAPHEAL

In [ ]:
x_test

PHONE_NUMBER MANAGER_ID     EMAIL
15  590.423.4560        103  VPATABAL
48  650.121.2019        123      JSEO
18  515.124.4169        108   DFAVIET
49  650.121.1834        123    JPATEL
9   515.123.4567         -      SKING
44  650.127.1734        122      KGEE
16  590.423.5567        103  DLORENTZ
28  515.127.4566        114  KCOLMENA
7   515.123.8080        101  SHIGGINS
1   650.507.9844        124    DGRANT